apiVersion: apps/v1 # control plane api version 
kind: Deployment # type of resources -- pod/service/ingress/deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashu-app
  name: ashu-app # name of deployment 
  namespace: ashu-space # namespace info 
spec:
  replicas: 2 # by default one replicas
  selector:
    matchLabels:
      app: ashu-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashu-app
    spec:
      containers:
      - image: docker.io/dockerashu/ashuciscoapp:v0011
        name: ashuciscoapp
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: always # adding this line
status: {}
